services:
  api:
    image: api
    build:
      context: .
      dockerfile: API/Dockerfile

  workerservice:
    image: workerservice
    build:
      context: .
      dockerfile: WorkerService/Dockerfile
